from typing import Any
from .engine import AttackPath

class PathExplanation:
    """
    Deterministic explainability layer for Neurobrain X.
    This module DOES NOT make detection decisions. It solely parses and translates
    the existing path evidence and scores generated by AttackReconstructor.
    """
    
    @staticmethod
    def generate(path: AttackPath) -> dict[str, Any]:
        report = {
            "confidence": round(path.confidence, 1),
            "decision": "",
            "evidence": [],
            "identity_analysis": {
                "device_continuity": False,
                "vpn_rotation_detected": False,
                "credential_risk": False,
                "identity_spoofing": False
            },
            "rejected_hypotheses": []
        }
        
        # Decision banding based strictly on confidence
        if path.confidence >= 90:
            report["decision"] = "HIGH_CONFIDENCE_ATTACK_PATH"
        elif path.confidence >= 70:
            report["decision"] = "MEDIUM_CONFIDENCE_ATTACK_PATH"
        else:
            report["decision"] = "LOW_CONFIDENCE_PATH"

        has_temporal = False
        has_network = False
        has_topology = False
        
        for edge in path.edges:
            # Parse identity continuity
            if "device_continuity" in edge.inference_reason:
                report["identity_analysis"]["device_continuity"] = True
            if "vpn_rotation_continuity" in edge.inference_reason:
                report["identity_analysis"]["device_continuity"] = True
                report["identity_analysis"]["vpn_rotation_detected"] = True
            if "stolen_credential_anomaly" in edge.inference_reason:
                report["identity_analysis"]["credential_risk"] = True
            if "spoofed_identity_contradiction" in edge.inference_reason:
                report["identity_analysis"]["identity_spoofing"] = True
                
            # Parse standard evidence
            if "Temporal proximity" in edge.inference_reason:
                has_temporal = True
            if "Network correlation" in edge.inference_reason:
                has_network = True
            if "Known topology" in edge.inference_reason:
                has_topology = True
                
            # Document contradictions that were overcome or rejected
            if "contradictory" in edge.inference_reason or "anomaly" in edge.inference_reason:
                report["rejected_hypotheses"].append({"reason": edge.inference_reason})
                
        if has_temporal:
            report["evidence"].append("Temporal correlation confirmed")
        if has_network:
            report["evidence"].append("Network correlation confirmed")
        if has_topology:
            report["evidence"].append("Topology relationship confirmed")
            
        if report["identity_analysis"]["device_continuity"]:
            report["evidence"].append("Identity continuity maintained")
        if report["identity_analysis"]["credential_risk"]:
            report["evidence"].append("Credential risk identified in continuity context")
            
        return report
